<template>
  <v-card class="mt-16 mx-16" style="">
    <v-card-text style="color: #A61c00; text-align: center; font-size: 36px;">Privacy Policy</v-card-text>
    <v-card-title>Effective: October 15, 2020</v-card-title>
    <v-card-text>This Privacy Policy describes how SOWerk collects, uses and discloses information, and what choices you have with respect to the information.</v-card-text>
    <v-card-text>When we refer to “SOWerk”, we mean the SOWerk entity that acts as the controller or processor of your information, as explained in more detail in the “Identifying the Data Controller and Processor” section below.</v-card-text>
    <v-card-title>Table of Contents:</v-card-title>
    <v-list>
      <v-list-item>Applicability of this Privacy Policy</v-list-item>
      <v-list-item>Information We Collect and Receive</v-list-item>
      <v-list-item>How We Use Information</v-list-item>
      <v-list-item>Data Retention</v-list-item>
      <v-list-item>How We Share and Disclose Information</v-list-item>
      <v-list-item>Security</v-list-item>
      <v-list-item>Age Limitations</v-list-item>
      <v-list-item>Changes to this Privacy Policy</v-list-item>
      <v-list-item>International Data Transfers</v-list-item>
      <v-list-item>Data Protection Officer</v-list-item>
      <v-list-item>Identifying the Data Controller and Processor</v-list-item>
      <v-list-item>Your Rights</v-list-item>
      <v-list-item>California Privacy Rights</v-list-item>
      <v-list-item>Data Protection Authority</v-list-item>
      <v-list-item>Contacting SOWerk</v-list-item>
    </v-list>
    <v-card-title>Applicability Of This Privacy Policy</v-card-title>
    <v-card-text>This Privacy Policy applies to SOWerk’s online vendor management tools and platform, including any associated SOWerk mobile and desktop applications (collectively, the “Services”), SOWerk.com and other SOWerk websites (collectively, the “Websites”) and other interactions (e.g., customer service inquiries, user conferences/meetings, etc.) you may have with SOWerk. If you do not agree with the terms, do not access or use the Services, Websites or any other aspect of SOWerk’s business.</v-card-text>
    <v-card-text>This Privacy Policy does not apply to any third party applications or software that integrate with the Services through the SOWerk platform (“Third Party Services”), or any other third party products, services or businesses. In addition, a separate agreement governs delivery, access and use of the Services (the “Customer Agreement”), including the processing of any messages, files or other content submitted through Services accounts (collectively, “Customer Data”). The organization (e.g., your employer or another entity or person) that entered into the Customer Agreement (“Customer”) controls its instance of the Services (its “SOWerk Account”) and any associated Customer Data. If you have any questions about specific SOWerk Account settings and privacy practices, please contact the Customer whose SOWerk Account you use. If you have received an invitation to join a SOWerk Account but have not yet created an account, you should request assistance from the Customer that sent the invitation.</v-card-text>
    <v-card-title>Information We Collect And Receive</v-card-title>
    <v-card-text>SOWerk may collect and receive Customer Data and other information and data (“Other Information”) in a variety of ways:</v-card-text>
    <v-list>
      <v-list-item>Customer Data. Customers or individuals granted access to a SOWerk Account by a Customer (“Authorized Users”) routinely submit Customer Data to SOWerk when using the Services.</v-list-item>
      <v-list-item>
        <v-list>
          <v-list-item-title>Other Information. SOWerk also collects, generates and/or receives Other Information:</v-list-item-title>
          <v-list-item>SOWerk Account and Account Information. To create or update a SOWerk account, you or your Customer (e.g., your employer) supply SOWerk with an email address, phone number, password, domain and/or similar account details. In addition, Customers that purchase a paid version of the Services provide SOWerk (or its payment processors) with billing details such as credit card information, banking information and/or a billing address.</v-list-item>
          <v-list-item>
            <v-list>
              <v-list-item-title>Usage Information.</v-list-item-title>
              <v-list-item>Services Metadata. When an Authorized User interacts with the Services, metadata is generated that provides additional context about the way Authorized Users work. For example, SOWerk logs the locations, vendor applications, vendor or business searches, people, features, content and links you view or interact with, the types of files you share on SOWerk, and what Third Party Services are used (if any).</v-list-item>
              <v-list-item>Log data. As with most websites and technology services delivered over the Internet, our servers automatically collect information when you access or use our Websites or Services and record it in log files. This log data may include the Internet Protocol (IP) address, the address of the web page visited before using the Website or Services, browser type and settings, the date and time the Services were used, information about browser configuration and plugins, language preferences and cookie data.</v-list-item>
              <v-list-item>Device information. SOWerk collects information about devices accessing the Services, including type of device, what operating system is used, device settings, application IDs, unique device identifiers and crash data. Whether we collect some or all of this Other Information often depends on the type of device used and its settings.</v-list-item>
              <v-list-item>Location information. We receive information from you, your Customer and other third-parties that helps us approximate your location. We may, for example, use a business address submitted by your employer, or an IP address received from your browser or device to determine approximate location. SOWerk may also collect location information from devices in accordance with the consent process provided by your device.</v-list-item>
            </v-list>
          </v-list-item>
          <v-list-item>Cookie Information. SOWerk uses a variety of cookies and similar technologies in our Websites and Services to help us collect Other Information.</v-list-item>
          <v-list-item>Third Party Services. A Customer can choose to permit or restrict Third Party Services for its SOWerk Account. Typically, Third Party Services are software that integrate with our Services, and a Customer can permit its Authorized Users to enable and disable these integrations for its SOWerk Account. SOWerk may also develop and offer SOWerk applications that connect the Services with a Third Party Service. Once enabled, the provider of a Third Party Service may share certain information with SOWerk. For example, if a cloud storage application is enabled to permit files to be imported to a SOWerk Account, we may receive the user name and email address of Authorized Users, along with additional information that the application has elected to make available to SOWerk to facilitate the integration. Authorized Users should check the privacy settings and notices in these Third Party Services to understand what data may be disclosed to SOWerk. When a Third Party Service is enabled, SOWerk is authorized to connect and access Other Information made available to SOWerk in accordance with our agreement with the Third Party Provider and any permission(s) granted by Customer (including, by its Authorized User(s)). We do not, however, receive or store passwords for any of these Third Party Services when connecting them to the Services. For more information on Third Party Services, click here.</v-list-item>
          <v-list-item>Contact Information. In accordance with the consent process provided by your device, any contact information that an Authorized User chooses to import (such as an address book from a device) is collected when using the Services.</v-list-item>
          <v-list-item>Third Party Data. SOWerk may receive data about organizations, industries, lists of companies that are customers, Website visitors, marketing campaigns and other matters related to our business from parent corporation(s), affiliates and subsidiaries, our partners, or others that we use to make our own information better or more useful. This data may be combined with Other Information we collect and might include aggregate-level data, such as which IP addresses correspond to zip codes or countries. Or it might be more specific: for example, how well an online marketing or email campaign performed.</v-list-item>
          <v-list-item>Additional Information Provided to SOWerk. We also receive Other Information when submitted to our Websites or in other ways, such as if you participate in a focus group, contest, activity or event, apply for a job, enroll in a certification program or other educational program hosted by SOWerk or a vendor, request support, interact with our social media accounts or otherwise communicate with SOWerk.</v-list-item>
        </v-list>
      </v-list-item>
      <v-list-item>Generally, no one is under a statutory or contractual obligation to provide any Customer Data or Other Information (collectively, “Information”). However, certain Information is collected automatically and, if some Information, such as SOWerk Account setup details, is not provided, we may be unable to provide the Services.</v-list-item>

    </v-list>
    <v-card-title>How We Use Information</v-card-title>
    <v-card-text>Customer Data will be used by SOWerk in accordance with Customer’s instructions, including any applicable terms in the Customer Agreement and Customer’s use of Services functionality, and as required by applicable law. SOWerk is a processor of Customer Data and Customer is the controller. Customer may, for example, use the Services to grant and remove access to a SOWerk Account, assign roles and configure settings, access, modify, export, share and remove Customer Data and otherwise apply its policies to the Services.</v-card-text>
    <v-card-text>SOWerk uses Other Information in furtherance of our legitimate interests in operating our Services, Websites and business. More specifically, SOWerk uses Other Information:</v-card-text>
    <v-list>
      <v-list-item>To provide, update, maintain and protect our Services, Websites and business. This includes use of Other Information to support delivery of the Services under a Customer Agreement, prevent or address service errors, security or technical issues, analyze and monitor usage, trends and other activities, or at an Authorized User’s request.</v-list-item>
      <v-list-item>As required by applicable law, legal process or regulation.</v-list-item>
      <v-list-item>To communicate with you by responding to your requests, comments and questions. If you contact us, we may use your Other Information to respond.</v-list-item>
      <v-list-item>To develop and provide search, learning and productivity tools and additional features. SOWerk tries to make the Services as useful as possible for specific SOWerk Accounts and Authorized Users. For example, we may improve search functionality by using Other Information to help determine and rank the relevance of content, channels or expertise to an Authorized User, make Services or Third Party Service suggestions based on historical use and predictive models, identify organizational trends and insights, to customize a Services experience, or create new productivity features and products.</v-list-item>
      <v-list-item>To send emails and other communications. We may send you service, technical and other administrative emails, messages, and other types of communications. We may also contact you to inform you about changes in our Services, our Services offerings, and important Services-related notices, such as security and fraud notices. These communications are considered part of the Services and you may not opt out of them. In addition, we sometimes send emails about new product features, promotional communications or other news about SOWerk. These are marketing messages so you can control whether you receive them. If you have additional questions about a message you have received from SOWerk please reach out through the contact mechanisms described below.</v-list-item>
      <v-list-item>For billing, account management and other administrative matters. SOWerk may need to contact you for invoicing, account management, and similar reasons and we use account data to administer accounts and keep track of billing and payments.</v-list-item>
      <v-list-item>To investigate and help prevent security issues and abuse.</v-list-item>
    </v-list>
    <v-card-text>If Information is aggregated or de-identified so that it is no longer reasonably associated with an identified or identifiable natural person, SOWerk may use it for any business purpose. To the extent Information is associated with an identified or identifiable natural person and is protected as personal data under applicable data protection law, it is referred to in this Privacy Policy as “Personal Data.”</v-card-text>
    <v-card-title>Data Retention</v-card-title>
    <v-card-text>SOWerk will retain Customer Data in accordance with a Customer’s instructions, including any applicable terms in the Customer Agreement and Customer’s use of Services functionality, and as required by applicable law. Depending on the Services plan, Customer may be able to customize its retention settings and apply those customized settings at the SOWerk Account level, channel level or other level. Customer may also apply different settings to messages, files or other types of Customer Data. The deletion of Customer Data and other use of the Services by Customer may result in the deletion and/or de-identification of certain associated Other Information. SOWerk may retain Other Information pertaining to you for as long as necessary for the purposes described in this Privacy Policy. This may include keeping your Other Information after you have deactivated your account for the period of time needed for SOWerk to pursue legitimate business interests, conduct audits, comply with (and demonstrate compliance with) legal obligations, resolve disputes, and enforce our agreements.</v-card-text>
    <v-card-title>How We Share And Disclose Information</v-card-title>
    <v-card-text>This section describes how SOWerk may share and disclose Information. Customers determine their own policies and practices for the sharing and disclosure of Information, and SOWerk does not control how they or any other third parties choose to share or disclose Information.</v-card-text>
    <v-list>
      <v-list-item>Customer’s Instructions. SOWerk will solely share and disclose Customer Data in accordance with a Customer’s instructions, including any applicable terms in the Customer Agreement and Customer’s use of Services functionality, and in compliance with applicable law and legal process.</v-list-item>
      <v-list-item>Displaying the Services. When an Authorized User submits Other Information, it may be displayed to other Authorized Users in the same or connected SOWerk Accounts. For example, an Authorized User’s email address may be displayed with their SOWerk Account profile.</v-list-item>
      <v-list-item>Collaborating with Others. The Services provide different ways for Authorized Users working in independent SOWerk Accounts to collaborate, such as SOWerk Requests or email interoperability. Other Information, such as an Authorized User’s profile Information, may be shared, subject to the policies and practices of the other SOWerk Account(s).</v-list-item>
      <v-list-item>Customer Access. Owners, administrators, Authorized Users, and other Customer representatives and personnel may be able to access, modify, or restrict access to Other Information. This may include, for example, your employer using Service features to export logs of SOWerk Account activity, or accessing or modifying your profile details.</v-list-item>
      <v-list-item>Third Party Service Providers and Partners. We may engage third party companies or individuals as service providers or business partners to process Other Information and support our business. These third parties may, for example, provide virtual computing and storage services, or we may share business information to develop strategic partnerships with Third Party Service providers to support our common customers.</v-list-item>
      <v-list-item>Third Party Services. Customer may enable or permit Authorized Users to enable Third Party Services. We require each Third Party Service to disclose all permissions for information access in the Services, but we do not guarantee that they do so. When enabled, SOWerk may share Other Information with Third Party Services. Third Party Services are not owned or controlled by SOWerk and third parties that have been granted access to Other Information may have their own policies and practices for its collection, use, and sharing. Please check the permissions, privacy settings, and notices for these Third Party Services or contact the provider for any questions.</v-list-item>
      <v-list-item>Corporate Affiliates. SOWerk may share Other Information with its corporate affiliates, parents and/or subsidiaries.</v-list-item>
      <v-list-item>During a Change to SOWerk’s Business. If SOWerk engages in a merger, acquisition, bankruptcy, dissolution, reorganization, sale of some or all of SOWerk’s assets or stock, financing, public offering of securities, acquisition of all or a portion of our business, a similar transaction or proceeding, or steps in contemplation of such activities, some or all Other Information may be shared or transferred, subject to standard confidentiality arrangements.</v-list-item>
      <v-list-item>Aggregated or De-identified Data. We may disclose or use aggregated or de-identified Other Information for any purpose. For example, we may share aggregated or de-identified Other Information with prospects or partners for business or research purposes, such as telling a prospective SOWerk customer the average amount of time spent within a typical SOWerk Account.</v-list-item>
      <v-list-item>To Comply with Laws. If we receive a request for information, we may disclose Other Information if we reasonably believe disclosure is in accordance with or required by any applicable law, regulation, or legal process.</v-list-item>
      <v-list-item>To enforce our rights, prevent fraud, and for safety. To protect and defend the rights, property, or safety of SOWerk or third parties, including enforcing contracts or policies, or in connection with investigating and preventing fraud or security issues.</v-list-item>
      <v-list-item>With Consent. SOWerk may share Other Information with third parties when we have consent to do so.</v-list-item>
    </v-list>
    <v-card-title>Security</v-card-title>
    <v-card-text>SOWerk takes security of data very seriously. SOWerk works hard to protect Other Information you provide from loss, misuse, and unauthorized access or disclosure. These steps take into account the sensitivity of the Other Information we collect, process and store, and the current state of technology. Given the nature of communications and information processing technology, SOWerk cannot guarantee that Information during transmission through the Internet or while stored on our systems or otherwise in our care will be absolutely safe from intrusion by others. When you click a link to a third-party site, you will be leaving our site and we don’t control or endorse what is on third-party sites.</v-card-text>
    <v-card-title>Age Limitations</v-card-title>
    To the extent prohibited by applicable law, SOWerk does not allow use of our Services and Websites by anyone younger than 16 years old. If you learn that anyone younger than 16 has unlawfully provided us with personal data, please contact us and we will take steps to delete such information.
    <v-card-title>Changes To This Privacy Policy</v-card-title>
    <v-card-text>SOWerk may change this Privacy Policy from time to time. Laws, regulations, and industry standards evolve, which may make those changes necessary, or we may make changes to our services or business. We will post the changes to this page and encourage you to review our Privacy Policy to stay informed. If we make changes that materially alter your privacy rights, SOWerk will provide additional notice, such as via email or through the Services. If you disagree with the changes to this Privacy Policy, you should deactivate your Services account. Contact the Customer if you wish to request the removal of Personal Data under their control.</v-card-text>
    <v-card-title>Data Protection Officer</v-card-title>
    <v-card-text>To communicate with our Data Protection Officer, please email Support@SOWerk.com.</v-card-text>
    <v-card-title>Identifying The Data Controller And Processor</v-card-title>
    <v-card-text>Data protection law in certain jurisdictions differentiates between the “controller” and “processor” of information. In general, Customer is the controller of Customer Data. In general, SOWerk is the processor of Customer Data and the controller of Other Information. Different SOWerk entities provide the Services in different parts of the world. SOWerk LLC., an Irish company based in Dublin, Ireland, is the controller of Other Information and a processor of Customer Data relating to Authorized Users who use SOWerk Accounts established for Customers outside of the U.S. and Canada. SOWerk LLC., a US company based in Springfield, Missouri is the controller of Other Information and a processor of Customer Data relating to Authorized Users who use SOWerk Accounts established for Customers in the US and Canada.</v-card-text>
    <v-card-title>Your Rights</v-card-title>
    <v-card-text>Individuals located in certain countries, including the European Economic Area and the United Kingdom, have certain statutory rights in relation to their personal data. Subject to any exemptions provided by law, you may have the right to request access to Information, as well as to seek to update, delete or correct this Information. You can do this by contacting the Customer who controls your SOWerk Account for additional access and assistance.</v-card-text>
    <v-card-text>To the extent that SOWerk’s processing of your Personal Data is subject to the General Data Protection Regulation (or applicable laws covering the processing of Personal Data in the United Kingdom), SOWerk relies on its legitimate interests, described above, to process your data. SOWerk may also process Other Information that constitutes your Personal Data for direct marketing purposes, and you have a right to object to SOWerk’s use of your Personal Data for this purpose at any time.</v-card-text>
    <v-card-title>Your California Privacy Rights</v-card-title>
    <v-card-text>This section provides additional details about the personal information we collect about California consumers and the rights afforded to them under the California Consumer Privacy Act or “CCPA.”</v-card-text>
    <v-card-text>For more details about the personal information we have collected over the last 12 months, including the categories of sources, please contact Support@SOWerk.com. We collect this information for the business and commercial purposes described in the How We Use Information section above. We share this information with the categories of third parties described in the How We Share and Disclose Information section above. SOWerk does not sell (as such term is defined in the CCPA) the personal information we collect (and will not sell it without providing a right to opt out). Please note that we do use third-party cookies for our advertising purposes.</v-card-text>
    <v-card-text>Subject to certain limitations, the CCPA provides California consumers the right to request to know more details about the categories or specific pieces of personal information we collect (including how we use and disclose this information), to delete their personal information, to opt out of any “sales” that may be occurring, and to not be discriminated against for exercising these rights.</v-card-text>
    <v-card-text>California consumers may make a request pursuant to their rights under the CCPA by contacting us at Support@SOWerk.com. We will verify your request using the information associated with your account, including email address. Government identification may be required. Consumers can also designate an authorized agent to exercise these rights on their behalf.</v-card-text>
    <v-card-title>Data Protection Authority</v-card-title>
    <v-card-text>Subject to applicable law, you also have the right to (i) restrict SOWerk’s use of Other Information that constitutes your Personal Data and (ii) lodge a complaint with your local data protection authority or the Irish Data Protection Commissioner, which is SOWerk’s lead supervisory authority in the European Union.</v-card-text>
    <v-card-title>Contacting SOWerk</v-card-title>
    <v-card-text>Please also feel free to contact SOWerk if you have any questions about this Privacy Policy or SOWerk’s practices, or if you are seeking to exercise any of your statutory rights. SOWerk will respond within a reasonable timeframe. You may contact us at Support@SOWerk.com or at our mailing address below:</v-card-text>
    <v-card-text>For Customers and Authorized Users who use SOWerk Accounts established for Customers in the US and Canada:</v-card-text>
    <v-card-text>SOWerk LLC</v-card-text>
    <v-card-text>405 N. Jefferson Ave. Suite 1010</v-card-text>
    <v-card-text>Springfield MO 65807</v-card-text>
  </v-card>
</template>

<script>
  export default {
    layout: 'fullwidth',
  }
</script>

<style>

</style>
