<template>
  <v-card class="mt-16 mx-16" style="">
    <v-card-text style="color: #A61c00; text-align: center; font-size: 36px;">Customer Terms</v-card-text>
    <v-card-title>Effective: October 15, 2020</v-card-title>
    <v-card-text>These Customer Terms of Service (the “<b>Customer Terms</b>”) describe your rights and responsibilities when using our online vendor management tools and platform (the “<b>Services</b>”). Please read them carefully. If you are a Customer (defined below), these Customer Terms govern your access and use of our Services. If you are being invited to use our Services by a Customer, the User Terms of Service (the “<b>User Terms</b>”) govern your access and use of the Services.</v-card-text>
    <v-card-title>First Things First</v-card-title>
    <v-card-subtitle>These “Customer Terms” Form a Part of a Binding “Contract”</v-card-subtitle>
    <v-card-text>These Customer Terms (or, if applicable, your written agreement with us) and any Order Form(s) (defined below) together form a binding “<b>Contract</b>” between Customer and us. If any terms in the Customer-Specific Supplement apply to Customer (e.g., if Customer is a U.S. government entity), those terms are also incorporated herein by reference and form part of the Contract. “We,” “our” and “us” refers to the applicable SOWerk entity in the section entitled “Which SOWerk Entity is Customer Contracting With?” below.</v-card-text>
    <v-card-subtitle>Your Agreement On Behalf of “Customer”</v-card-subtitle>
    <v-card-text>If you purchase subscription(s), upgrade a free base level (to incorporate more connections or otherwise additional platform features not generally available for free to Customers), invite users to join SOWerk, or use or allow use of said account after being notified of a change to these Customer Terms, you acknowledge your understanding of the then-current Contract and agree to the Contract on behalf of Customer. Please make sure you have the necessary authority to enter into the Contract on behalf of Customer before proceeding.</v-card-text>
    <v-card-title>Customer Choices and Instructions</v-card-title>
    <v-card-subtitle>Who is “Customer”? (Hint: There can be only one)</v-card-subtitle>
    <v-card-text>“Customer” is the organization that you represent in agreeing to the Contract. If your SOWerk account is being set up by someone who is not formally affiliated with an organization, Customer is the individual creating the account. For example, if you signed up using a personal email address and invited a couple of friends to work on a new startup and need to see what kind of vendors and businesses are on SOWerk but haven't formed a company yet, you are the Customer.</v-card-text>
    <v-card-subtitle>Signing Up Using a Corporate Email Domain</v-card-subtitle>
    <v-card-text>If you signed up for an account or subscription plan using your corporate email domain, your organization is Customer, and Customer can modify and re-assign roles on your account (including your role) and otherwise exercise its rights under the Contract. If Customer elects to replace you as the representative with ultimate authority for the account, we will provide you with notice following such election and you agree to take any actions reasonably requested by us or Customer to facilitate the transfer of authority to a new representative of Customer.</v-card-text>
    <v-card-subtitle>What This Means for Customer—and for Us</v-card-subtitle>
    <v-card-text>Individuals authorized by Customer to access the Services (an “<b>Authorized User</b>”) may submit content or information to the Services, such as vendor/partner requirements or files (“<b>Customer Data</b>”), and Customer may exclusively provide us with instructions on what to do with it. For example, Customer may provision or deprovision access to the Services, enable or disable third party integrations, manage permissions, retention and export settings, transfer or assign accounts, share account management, or consolidate accounts with other accounts. Since these choices and instructions may result in the access, use, disclosure, modification or deletion of certain or all Customer Data, please review the Help Center pages for more information about these choices and instructions.</v-card-text>
    <v-card-text>Customer will (a) inform Authorized Users of all Customer policies and practices that are relevant to their use of the Services and of any settings that may impact the processing of Customer Data; and (b) ensure the transfer and processing of Customer Data under the Contract is lawful.</v-card-text>
    <v-card-subtitle>Ordering Subscriptions</v-card-subtitle>
    <v-card-text>A subscription allows an Authorized User to access the Services. SOWerk offers Services at a basic free level for businesses seeking vendors and vendors providing a product or service for sale (“<b>Account Type</b>”). No matter the Account Type, a subscription is required for each Authorized User when accessing Services beyond basic free level. A subscription may be procured through the Services interface, or in some cases, via an order form entered into between Customer and us (each, an “<b>Order Form</b>”). Each Customer account must agree to the User Terms to activate their subscription. Subscriptions commence when we make them available to Customer and continue for the term specified in the Services “check-out” interface or in the Order Form, as applicable. We sometimes enter into other kinds of ordering arrangements, but that would need to be spelled out and agreed to in an Order Form. During an active subscription term, adding more subscriptions is fairly easy. Unless the Order Form says otherwise, Customer may purchase more subscriptions at the same price stated in the Order Form and all will terminate on the same date. </v-card-text>
    <v-card-subtitle>Purchasing Decisions</v-card-subtitle>
    <v-card-text>We may share information about our future product plans because we like transparency. Our public statements about those product plans are an expression of intent, but do not rely on them when making a purchase. If Customer decides to buy our Services, that decision should be based on the functionality or features we have made available today and not on the delivery of any future functionality or features.</v-card-text>
    <v-card-text>Choosing to be a Beta Tester</v-card-text>
    <v-card-text>Occasionally, we look for beta testers to help us test our new features. These features will be identified as “beta” or “pre-release,” or words or phrases with similar meanings (each, a “<b>Beta Product</b>”). Beta Products may not be ready for prime time so they are made available “as is,” and any warranties or contractual commitments we make for other Services do not apply. Should Customer encounter any faults with our Beta Products, we would love to hear about them; our primary reason for running any beta programs is to iron out issues before making a new feature widely available.</v-card-text>
    <v-card-subtitle>Feedback is Welcome</v-card-subtitle>
    <v-card-text>The more suggestions our customers make, the better the Services become. If Customer sends us any feedback or suggestions regarding the Services, there is a chance we will use it, so Customer grants us (for itself and all of its Authorized Users and other Customer personnel) an unlimited, irrevocable, perpetual, sublicensable, transferable, royalty-free license to use any such feedback or suggestions for any purpose without any obligation or compensation to Customer, any Authorized User or other Customer personnel. If we choose not to implement the suggestion, please don’t take it personally. We appreciate it nonetheless.</v-card-text>
    <v-card-subtitle>Non-SOWerk Products</v-card-subtitle>
    <v-card-text>Our Services include a platform that third parties may use to develop applications and software that complement Customer’s use of the Services (each, a “<b>Non-SOWerk Product</b>”). We also maintain a directory called the SOWerk App Directory where some Non-SOWerk Products are available for installation. THESE ARE NOT OUR SERVICES, SO WE DO NOT WARRANT OR SUPPORT NON-SOWERK PRODUCTS, AND, ULTIMATELY, CUSTOMER (AND NOT US) WILL DECIDE WHETHER OR NOT TO ENABLE THEM. ANY USE OF A NON-SOWERK PRODUCT IS SOLELY BETWEEN CUSTOMER AND THE APPLICABLE THIRD PARTY PROVIDER.</v-card-text>
    <v-card-text>If a Non-SOWerk Product is enabled for Customer’s account, please be mindful of any Customer Data that will be shared with the third party provider and the purposes for which the provider requires access. We will not be responsible for any use, disclosure, modification or deletion of Customer Data that is transmitted to, or accessed by, a Non-SOWerk Product. Check out our<span style="color:blue;"><u> Help Center</u></span> pages for more information.</v-card-text>
    <v-card-subtitle>Privacy Policy</v-card-subtitle>
    <v-card-text>Please review our <span style="color:blue;"><u>Privacy Policy</u></span> for more information on how we collect and use data relating to the use and performance of our websites and products.</v-card-text>
    <v-card-title>Customer and Authorized Users</v-card-title>
    <v-card-subtitle>Use of the Services</v-card-subtitle>
    <v-card-text>Customer must comply with the Contract and ensure that its Authorized Users comply with the Contract and the User Terms. We may review conduct for compliance purposes, but we have no obligation to do so. We aren't responsible for the content of any Customer Data or the way Customer or its Authorized Users choose to use the Services to store or process any Customer Data. The Services are not intended for and should not be used by anyone under the age of 16. Customer must ensure that all Authorized Users are over 16 years old. Customer is solely responsible for providing high speed internet service for itself and its Authorized Users to access and use the Services.</v-card-text>
    <v-card-subtitle>Our Removal Rights</v-card-subtitle>
    <v-card-text>If we believe that there is a violation of the Contract that can simply be remedied by Customer’s removal of certain Customer Data or Customer’s disabling of a Non-SOWerk Product, we will, in most cases, ask Customer to take direct action rather than intervene. However, we may directly step in and take what we determine to be appropriate action, if Customer does not take appropriate action, or if we believe there is a credible risk of harm to us, the Services, Authorized Users, or any third parties.</v-card-text>
    <v-card-title>Payment Obligations</v-card-title>
    <v-card-subtitle>Payment Terms</v-card-subtitle>
    <v-card-text>For Customers that purchase our Services, fees are specified at the Services interface “check-out” and in the Order Form(s) — and must be paid in advance. Payment obligations are non-cancelable and, except as expressly stated in the Contract, fees paid are non-refundable. For clarity, in the event Customer downgrades any subscriptions from a paid plan to a free plan, Customer will remain responsible for any unpaid fees under the paid plan, and Services under the paid plan will be deemed fully performed and delivered upon expiration of the initial paid plan subscription term. If we agree to invoice Customer by email, full payment must be received within thirty (30) days from the invoice date. Fees are stated exclusive of any taxes, levies, duties, or similar governmental assessments of any nature, including, for example, value-added, sales, use or withholding taxes, assessable by any jurisdiction (collectively, “<b>Taxes</b>”). Customer will be responsible for paying all Taxes associated with its purchases. Should any payment for the Services be subject to withholding tax by any government, Customer will reimburse us for such withholding tax.</v-card-text>
    <v-card-subtitle>Credits</v-card-subtitle>
    <v-card-text>Any credits that may accrue to Customer’s account will expire following expiration or termination of the applicable Contract, will have no currency or exchange value, and will not be transferable or refundable. Credits accrued to an account on a free subscription plan will expire if the account’s plan is not upgraded to a paid plan within ninety (90) days of accrual, unless otherwise specified. </v-card-text>
    <v-card-subtitle>Downgrade for Non-Payment</v-card-subtitle>
    <v-card-text>If any fees owed to us by Customer (excluding amounts disputed reasonably and in good faith) are thirty (30) days or more overdue, we may, without limiting our other rights and remedies, downgrade any fee-based Services to free plans until those amounts are paid in full, so long as we have given Customer ten (10) or more days’ prior notice that its account is overdue. Notwithstanding the second paragraph of the “Providing the Services” section below, Customer acknowledges and agrees that a downgrade will result in a decrease in certain features and functionality and potential loss of access to Customer Data, as illustrated by comparing the plans. </v-card-text>
    <v-card-title>Our Responsibilities</v-card-title>
    <v-card-subtitle>Providing the Services</v-card-subtitle>
    <v-card-text>Customer isn’t the only one with responsibilities; we have some, too. We will (a) make the Services available to Customer and its Authorized Users as described in the Contract; and (b) not use or process Customer Data for any purpose without Customer’s prior written instructions; provided, however, that “prior written instructions” will be deemed to include use of the Services by Authorized Users and any processing related to such use or otherwise necessary for the performance of the Contract.</v-card-text>
    <v-card-text>Be assured that (a) the Services will perform materially in accordance with our then-current documentation publicly provided; and (b) subject to the “Non-SOWerk Products” and “Downgrade for Non-Payment” sections, we will not materially decrease the functionality of a Service during a subscription term. For any breach of a warranty in this section, Customer’s exclusive remedies are those described in the sections titled “Termination for Cause” and “Effect of Termination”.</v-card-text>
    <v-card-subtitle>Keeping the Services Available</v-card-subtitle>
    <v-card-text>As further described in our documentation provided publicly, for some of our Services, we also offer specific uptime commitments paired with credits, if we fall short. In those cases, the credits will serve as what the lawyers call liquidated damages and will be Customer’s sole remedy for the downtime and related inconvenience. For all Service plans, we will use commercially reasonable efforts to make the Services available 24 hours a day, 7 days a week, excluding planned downtime. We expect planned downtime to be infrequent but will endeavor to provide Customer with advance notice (e.g., through the Services), if we think it may exceed five (5) continuous minutes.</v-card-text>
    <v-card-subtitle>Protecting Customer Data</v-card-subtitle>
    <v-card-text>The protection of Customer Data is a top priority for us so we will maintain administrative, physical, and technical safeguards at a level not materially less protective than as described in our <span style="color:blue;"><u>Security Practices</u></span> page. Those safeguards will include measures for preventing unauthorized access, use, modification, deletion and disclosure of Customer Data by our personnel. Before sharing Customer Data with any of our third party service providers, we will ensure that the third party maintains, at a minimum, reasonable data practices for maintaining the confidentiality and security of Customer Data and preventing unauthorized access. Customer (not us) bears sole responsibility for adequate security, protection and backup of Customer Data when in Customer’s or its representatives’ or agents’ possession or control. We are not responsible for what Customer’s Authorized Users or Non-SOWerk Products do with Customer Data. That is Customer’s responsibility.</v-card-text>
    <v-card-subtitle>The SOWerk Extended Family</v-card-subtitle>
    <v-card-text>We may leverage our employees, those of our corporate affiliates and third party contractors (the “<b>SOWerk Extended Family</b>”) in exercising our rights and performing our obligations under the Contract. We will be responsible for the SOWerk Extended Family’s compliance with our obligations under the Contract.</v-card-text>
    <v-card-title>Ownership and Proprietary Rights</v-card-title>
    <v-card-subtitle>What’s Yours is Yours…</v-card-subtitle>
    <v-card-text>As between us on the one hand, and Customer and any Authorized Users on the other, Customer will own all Customer Data. Subject to the terms and conditions of the Contract, Customer (for itself and all of its Authorized Users) grants us and the SOWerk Extended Family a worldwide, non-exclusive, limited term license to access, use, process, copy, distribute, perform, export and display Customer Data, and any Non-SOWerk Products created by or for Customer, only as reasonably necessary (a) to provide, maintain and update the Services; (b) to prevent or address service, security, support or technical issues; (c) as required by law or as permitted by the <span style="color:blue;"><u>Data Request Policy</u></span>; and (d) as expressly permitted in writing by Customer. Customer represents and warrants that it has secured all rights in and to Customer Data from its Authorized Users as may be necessary to grant this license.</v-card-text>
    <v-card-subtitle>And What’s Ours is Ours</v-card-subtitle>
    <v-card-text>We own and will continue to own our Services, including all related intellectual property rights. We may make software components available, via app stores or other channels, as part of the Services. We grant to Customer a non-sublicensable, non-transferable, non-exclusive, limited license for Customer and its Authorized Users to use the object code version of these components, but solely as necessary to use the Services and in accordance with the Contract and the User Terms. All of our rights not expressly granted by this license are hereby retained.</v-card-text>
    <v-card-title>Term and Termination</v-card-title>
    <v-card-subtitle>Contract Term</v-card-subtitle>
    <v-card-text>As further described below, a free subscription continues until terminated, while a paid subscription has a term that may expire or be terminated. The Contract remains effective until all subscriptions ordered under the Contract have expired or been terminated or the Contract itself terminates. Termination of the Contract will terminate all subscriptions and all Order Forms.</v-card-text>
    <v-card-subtitle>Auto-Renewal</v-card-subtitle>
    <v-card-text>Unless an Order Form says something different, (a) all subscriptions automatically renew (without the need to go through the Services-interface “check-out” or execute a renewal Order Form) for additional periods equal to one (1) year or the preceding term, whichever is shorter; and (b) the per-unit pricing during any automatic renewal term will remain the same as it was during the immediately prior term. Either party can give the other notice of non-renewal at least thirty (30) days before the end of a subscription term to stop the subscriptions from automatically renewing.</v-card-text>
    <v-card-subtitle>Termination for Cause</v-card-subtitle>
    <v-card-text>We or Customer may terminate the Contract on notice to the other party if the other party materially breaches the Contract and such breach is not cured within thirty (30) days after the non-breaching party provides notice of the breach. Customer is responsible for its Authorized Users, including for any breaches of this Contract caused by its Authorized Users. We may terminate the Contract immediately on notice to Customer if we reasonably believe that the Services are being used by Customer or its Authorized Users in violation of applicable law.</v-card-text>
    <v-card-subtitle>Termination Without Cause</v-card-subtitle>
    <v-card-text>Customer may terminate its free subscriptions immediately without cause. We may also terminate Customer’s free subscriptions without cause, but we will provide Customer with thirty (30) days prior written notice.</v-card-text>
    <v-card-subtitle>Effect of Termination</v-card-subtitle>
    <v-card-text>Upon any termination for cause by Customer, we will refund Customer any prepaid fees covering the remainder of the term of all subscriptions after the effective date of termination. Upon any termination for cause by us, Customer will pay any unpaid fees covering the remainder of the term of those subscriptions after the effective date of termination. In no event will any termination relieve Customer of the obligation to pay any fees payable to us for the period prior to the effective date of termination.</v-card-text>
    <v-card-subtitle>Data Portability and Deletion</v-card-subtitle>
    <v-card-text>We are custodians of Customer Data. During the term of a account’s subscriptions, Customer will be permitted to share certain Customer Data from the Services; provided, however, that because we have different products with varying features and Customer has different retention options, Customer acknowledges and agrees that the ability to export or share Customer Data may be limited or unavailable depending on the type of Services plan in effect and the data retention, sharing or invite settings enabled. Following termination or expiration of an account’s subscriptions, we will have no obligation to maintain or provide any Customer Data and may thereafter, unless legally prohibited, delete all Customer Data in our systems or otherwise in our possession or under our control. Please review our <span style="color:blue;"><u>Security Practices</u></span> page for more information on how Customer itself can initiate deletion.</v-card-text>
    <v-card-title>Representations Disclaimer of Warranties</v-card-title>
    <v-card-text>Customer represents and warrants that it has validly entered into the Contract and has the legal power to do so. Customer further represents and warrants that it is responsible for the conduct of its Authorized Users and their compliance with the terms of this Contract and the User Terms.</v-card-text>
    <v-card-text>EXCEPT AS EXPRESSLY PROVIDED FOR HEREIN, THE SERVICES AND ALL RELATED COMPONENTS AND INFORMATION ARE PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS WITHOUT ANY WARRANTIES OF ANY KIND, AND WE EXPRESSLY DISCLAIM ANY AND ALL WARRANTIES, WHETHER EXPRESS OR IMPLIED, INCLUDING THE IMPLIED WARRANTIES OF MERCHANTABILITY, TITLE, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. CUSTOMER ACKNOWLEDGES THAT WE DO NOT WARRANT THAT THE SERVICES WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE.</v-card-text>
    <v-card-title>Limitation of Liability</v-card-title>
    <v-card-text>OTHER THAN IN CONNECTION WITH A PARTY’S INDEMNIFICATION OBLIGATIONS HEREUNDER, IN NO EVENT WILL EITHER CUSTOMER’S OR THE SOWERK EXTENDED FAMILY’S AGGREGATE LIABILITY ARISING OUT OF OR RELATED TO THE CONTRACT OR THE USER TERMS (WHETHER IN CONTRACT OR TORT OR UNDER ANY OTHER THEORY OF LIABILITY) EXCEED THE TOTAL AMOUNT PAID BY CUSTOMER HEREUNDER IN THE TWELVE (12) MONTHS PRECEDING THE LAST EVENT GIVING RISE TO LIABILITY. THE FOREGOING WILL NOT LIMIT CUSTOMER’S PAYMENT OBLIGATIONS UNDER THE “PAYMENT TERMS” SECTION ABOVE</v-card-text>
    <v-card-text>IN NO EVENT WILL EITHER CUSTOMER OR ANY MEMBER OF THE SOWERK EXTENDED FAMILY HAVE ANY LIABILITY TO THE OTHER PARTY OR TO ANY THIRD PARTY FOR ANY LOST PROFITS OR REVENUES OR FOR ANY INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL, COVER OR PUNITIVE DAMAGES HOWEVER CAUSED, WHETHER IN CONTRACT, TORT OR UNDER ANY OTHER THEORY OF LIABILITY, AND WHETHER OR NOT THE PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. THE FOREGOING DISCLAIMER WILL NOT APPLY TO THE EXTENT PROHIBITED BY APPLICABLE LAW.</v-card-text>
    <v-card-text>The Services support logins using two-factor authentication (“2FA”), which is known to reduce the risk of unauthorized use of or access to the Services. We therefore will not be responsible for any damages, losses or liability to Customer, Authorized Users, or anyone else if any event leading to such damages, losses or liability would have been prevented by the use of 2FA. Additionally, Customer is responsible for all login credentials, including usernames and passwords, for administrator accounts as well the accounts of your Authorized Users. We will not be responsible for any damages, losses or liability to Customer, Authorized Users, or anyone else, if such information is not kept confidential by Customer or its Authorized Users, or if such information is correctly provided by an unauthorized third party logging into and accessing the Services.</v-card-text>
    <v-card-text>The limitations under this “Limitation of Liability” section apply with respect to all legal theories, whether in contract, tort or otherwise, and to the extent permitted by law. The provisions of this “Limitation of Liability” section allocate the risks under this Contract between the parties, and the parties have relied on these limitations in determining whether to enter into this Contract and the pricing for the Services.</v-card-text>
    <v-card-title>Our Indemnification of Customer</v-card-title>
    <v-card-text>We will defend Customer from and against any and all third party claims, actions, suits, proceedings, and demands alleging that the use of the Services as permitted under the Contract infringes or misappropriates a third party’s intellectual property rights (a “<b>Claim Against Customer</b>”), and will indemnify Customer for all reasonable attorney’s fees incurred and damages and other costs finally awarded against Customer in connection with or as a result of, and for amounts paid by Customer under a settlement we approve of in connection with, a Claim Against Customer; provided, however, that we will have no liability if a Claim Against Customer arises from (a) Customer Data or Non-SOWerk Products; and (b) any modification, combination or development of the Services that is not performed by us, including in the use of any application programming interface (API). Customer must provide us with prompt written notice of any Claim Against Customer and allow us the right to assume the exclusive defense and control, and cooperate with any reasonable requests assisting our defense and settlement of such matter. This section states our sole liability with respect to, and Customer’s exclusive remedy against us and the SOWerk Extended Family for, any Claim Against Customer.</v-card-text>
    <v-card-title>Customer's Indemnification of Us</v-card-title>
    <v-card-text>(collectively, the “<b>SOWerk Indemnified Parties</b>”) from and against any and all third party claims, actions, suits, proceedings, and demands arising from or related to Customer’s or any of its Authorized Users’ violation of the Contract or the User Terms (a “<b>Claim Against Us</b>”), and will indemnify the SOWerk Indemnified Parties for all reasonable attorney’s fees incurred and damages and other costs finally awarded against a SOWerk Indemnified Party in connection with or as a result of, and for amounts paid by a SOWerk Indemnified Party under a settlement Customer approves of in connection with, a Claim Against Us. We must provide Customer with prompt written notice of any Claim Against Us and allow Customer the right to assume the exclusive defense and control, and cooperate with any reasonable requests assisting Customer’s defense and settlement of such matter. This section states your sole liability with respect to, and the SOWerk Indemnified Parties’ exclusive remedy against Customer for, any Claim Against Us.</v-card-text>
    <v-card-title>Limitations on Indemnifications</v-card-title>
    <v-card-text>Notwithstanding anything contained in the two preceding sections, (a) an indemnified party will always be free to choose its own counsel if it pays for the cost of such counsel; and (b) no settlement may be entered into by an indemnifying party, without the express written consent of the indemnified parties (such consent not to be unreasonably withheld), if (i) the third party asserting the claim is a government agency, (ii) the settlement arguably involves the making of admissions by the indemnified parties, (iii) the settlement does not include a full release of liability for the indemnified parties, or (iv) the settlement includes terms other than a full release of liability for the indemnified parties and the payment of money.</v-card-text>
    <v-card-title>Confidentiality</v-card-title>
    <v-card-subtitle>Confidential Information</v-card-subtitle>
    <v-card-text>Each party (“<b>Disclosing Party</b>”) may disclose “<b>Confidential Information</b>” to the other party (“<b>Receiving Party</b>”) in connection with the Contract, which is anything that reasonably should be understood to be confidential given the nature of the information and the circumstances of disclosure including all Order Forms, as well as non-public business, product, technology and marketing information.Confidential Information of Customer includes Customer Data. If something is labeled “Confidential,” that’s a clear indicator to the Receiving Party that the material is confidential. Notwithstanding the above, Confidential Information does not include information that (a) is or becomes generally available to the public without breach of any obligation owed to the Disclosing Party; (b) was known to the Receiving Party prior to its disclosure by the Disclosing Party without breach of any obligation owed to the Disclosing Party; (c) is received from a third party without breach of any obligation owed to the Disclosing Party; or (d) was independently developed by the Receiving Party.</v-card-text>
    <v-card-subtitle>Protection and Use of Confidential Information</v-card-subtitle>
    <v-card-text>The Receiving Party will (a) take at least reasonable measures to prevent the unauthorized disclosure or use of Confidential Information, and limit access to those employees, affiliates and contractors who need to know such information in connection with the Contract; and (b) not use or disclose any Confidential Information of the Disclosing Party for any purpose outside the scope of this Contract. Nothing above will prevent either party from sharing Confidential Information with financial and legal advisors; provided, however, that the advisors are bound to confidentiality obligations at least as restrictive as those in the Contract.</v-card-text>
    <v-card-subtitle>Compelled Access or Disclosure</v-card-subtitle>
    <v-card-text>The Receiving Party may access or disclose Confidential Information of the Disclosing Party if it is required by law; provided, however, that the Receiving Party gives the Disclosing Party prior notice of the compelled access or disclosure (to the extent legally permitted) and reasonable assistance, at the Disclosing Party's cost, if the Disclosing Party wishes to contest the access or disclosure. Without limiting the foregoing, please review the <span style="color:blue;"><u>Data Request Policy</u></span> for details on how requests may be made for the disclosure of Customer Data and how we will handle those requests. If the Receiving Party is compelled by law to access or disclose the Disclosing Party’s Confidential Information, the Disclosing Party will reimburse the Receiving Party for its reasonable cost of compiling and providing access to such Confidential Information as well as the reasonable cost for any support provided in connection with the Disclosing Party seeking a protective order or confidential treatment for the Confidential Information to be produced.</v-card-text>
    <v-card-title>Survival</v-card-title>
    <v-card-text>The sections titled “Feedback is Welcome,” “Non-SOWerk Products,” “Our Removal Rights,” “Use of the Services,” “Payment Terms,” “Credits,” “The SOWerk Extended Family,” “What’s Yours is Yours…,” “And What’s Ours is Ours,” “Effect of Termination,” “Data Portability and Deletion,” “Representations; Disclaimer of Warranties,” “Limitation of Liability,” “Our Indemnification of Customer,” “Customer’s Indemnification of Us,” “Limitations on Indemnifications,” “Confidentiality” and “Survival,” as well as all of the provisions under the general heading “General Provisions,” will survive any termination or expiration of the Contract.</v-card-text>
    <v-card-title>General Provisions</v-card-title>
    <v-card-subtitle>Publicity</v-card-subtitle>
    <v-card-text>Customer grants us the right to use Customer’s company name and logo as a reference for marketing or promotional purposes on our website and in other public or private communications with our existing or potential customers, subject to Customer’s standard trademark usage guidelines as provided to us from time-to-time. We don’t want to list customers who don’t want to be listed, so Customer may send us an email to <a href="mailto:support@sowerk.com">support@SOWerk.com</a> stating that it does not wish to be used as a reference.</v-card-text>
    <v-card-subtitle>Force Majeure</v-card-subtitle>
    <v-card-text>Neither us nor Customer will be liable by reason of any failure or delay in the performance of its obligations on account of events beyond the reasonable control of a party, which may include denial-of-service attacks, a failure by a third party hosting provider or utility provider, strikes, shortages, riots, fires, acts of God, war, terrorism, and governmental action.</v-card-text>
    <v-card-subtitle>Relationship of the Parties; No Third Party Beneficiaries</v-card-subtitle>
    <v-card-text>The parties are independent contractors. The Contract does not create a partnership, franchise, joint venture, agency, fiduciary or employment relationship between the parties. There are no third party beneficiaries to the Contract.</v-card-text>
    <v-card-subtitle>Email and SOWerk Messages</v-card-subtitle>
    <v-card-text>Except as otherwise set forth herein, all notices under the Contract will be by email, although we may instead choose to provide notice to Customer through the Services (e.g., a website message/notification). Notices to SOWerk will be sent to Support@SOWerk.com, except for legal notices, such as notices of termination or an indemnifiable claim, which must be sent to <a href="mailto:legal@sowerk.com">legal@SOWerk.com</a>. Notices will be deemed to have been duly given (a) the day after it is sent, in the case of notices through email; and (b) the same day, in the case of notices through the Services.</v-card-text>
    <v-card-subtitle>Modifications</v-card-subtitle>
    <v-card-text>As our business evolves, we may change these Customer Terms and the other components of the Contract (except any Order Forms). If we make a material change to the Contract, we will provide Customer with reasonable notice prior to the change taking effect, either by emailing the email address associated with Customer’s account or by messaging Customer through the Services. Customer can review the most current version of the Customer Terms at any time by visiting this page and by visiting the most current versions of the other pages that are referenced in the Contract. The materially revised Contract will become effective on the date set forth in our notice, and all other changes will become effective upon posting of the change. If Customer (or any Authorized User) accesses or uses the Services after the effective date, that use will constitute Customer’s acceptance of any revised terms and conditions.</v-card-text>
    <v-card-subtitle>Waiver</v-card-subtitle>
    <v-card-text>No failure or delay by either party in exercising any right under the Contract will constitute a waiver of that right. No waiver under the Contract will be effective unless made in writing and signed by an authorized representative of the party being deemed to have granted the waiver.</v-card-text>
    <v-card-subtitle>Severability</v-card-subtitle>
    <v-card-text>The Contract will be enforced to the fullest extent permitted under applicable law. If any provision of the Contract is held by a court of competent jurisdiction to be contrary to law, the provision will be modified by the court and interpreted so as best to accomplish the objectives of the original provision to the fullest extent permitted by law, and the remaining provisions of the Contract will remain in effect.</v-card-text>
    <v-card-subtitle>Assignment</v-card-subtitle>
    <v-card-text>Except with respect to the SOWerk Extended Family, neither party may assign or delegate any of its rights or obligations hereunder, whether by operation of law or otherwise, without the prior written consent of the other party (not to be unreasonably withheld). Notwithstanding the foregoing, either party may assign the Contract in its entirety (including all Order Forms), without consent of the other party, to a corporate affiliate or in connection with a merger, acquisition, corporate reorganization, or sale of all or substantially all of its assets. Customer will keep its billing and contact information current at all times by notifying SOWerk of any changes. Any purported assignment in violation of this section is void. A party’s sole remedy for any purported assignment by the other party in breach of this section will be, at the non-assigning party’s election, termination of the Contract upon written notice to the assigning party. In the event of such a termination by Customer, we will refund Customer any prepaid fees covering the remainder of the term of all subscriptions after the effective date of termination. Subject to the foregoing, the Contract will bind and inure to the benefit of the parties, their respective successors and permitted assigns.</v-card-text>
    <v-card-subtitle>Which SOWerk Entity is Customer Contracting With?</v-card-subtitle>
    <v-card-text>All references to ‘SOWerk,’ ‘we,’ or ‘us’ under the Contract, what law will apply in any dispute or lawsuit arising out of or in connection with the Contract, and which courts have jurisdiction over any such dispute or lawsuit, depend on where Customer is domiciled.</v-card-text>
    <v-row class="mx-auto d-flex justify-space-between">
    <v-col cols="3">
      <v-row>
        <v-card-text>
          <b>Domicile</b>
        </v-card-text>
      </v-row>
      <v-row>
        <v-card-text>
          United States and Canada
        </v-card-text>
      </v-row>
    </v-col>
     <v-col cols="3">
      <v-row>
        <v-card-text>
         <b>SOWerk Contracting Entity</b>
        </v-card-text>
      </v-row>
      <v-row>
        <v-card-text>
          SOWerk LLC.
        </v-card-text>
      </v-row>
    </v-col>
     <v-col cols="3">
      <v-row>
        <v-card-text>
          <b>Governing Law</b>
        </v-card-text>
      </v-row>
      <v-row>
        <v-card-text>
          Missouri
        </v-card-text>
      </v-row>
    </v-col>
     <v-col cols="3">
      <v-row>
        <v-card-text>
          <b>Venue</b>
        </v-card-text>
      </v-row>
      <v-row>
        <v-card-text>
          Cole County Missouri
        </v-card-text>
      </v-row>
    </v-col>
    </v-row>
    <v-card-text>The Contract, and any disputes arising out of or related hereto, will be governed exclusively by the applicable governing law above, without regard to conflicts of laws rules or the United Nations Convention on the International Sale of Goods. The courts located in the applicable venue above will have exclusive jurisdiction to adjudicate any dispute arising out of or relating to the Contract or its formation, interpretation or enforcement. Each party hereby consents and submits to the exclusive jurisdiction of such courts. In any action or proceeding to enforce rights under the Contract, the prevailing party will be entitled to recover its reasonable costs and attorney’s fees.</v-card-text>
    <v-card-subtitle>Entire Agreement</v-card-subtitle>
    <v-card-text>The Contract, including these Customer Terms and all referenced pages and Order Forms, if applicable, constitutes the entire agreement between the parties and supersedes all prior and contemporaneous agreements, proposals or representations, written or oral, concerning its subject matter. Without limiting the foregoing, the Contract supersedes the terms of any online agreement electronically accepted by Customer or any Authorized Users. However, to the extent of any conflict or inconsistency between the provisions in these Customer Terms and any other documents or pages referenced in these Customer Terms, the following order of precedence will apply: (1) the terms of any Order Form (if any), (2) the portions of the <span style="color:blue;"><u>Customer-Specific Supplement</u> </span>that apply to Customer (if any), (3) the Customer Terms and (4) finally any other documents or pages referenced in the Customer Terms. Notwithstanding any language to the contrary therein, no terms or conditions stated in a Customer purchase order, vendor onboarding process or web portal, or any other Customer order documentation (excluding Order Forms) will be incorporated into or form any part of the Contract, and all such terms or conditions will be null and void.</v-card-text>


  </v-card>
</template>

<script>
  export default {
    layout: 'fullwidth',
  }
</script>

<style>

</style>
